% SPDX-License-Identifier: AGPL-3.0-only
% Copyright (C) 2026 David contributors
% GENERATED by scripts/gen_registry_facts.py from registry/seed_agents.yaml
% Do not edit by hand — regenerate via scripts/check_prolog_registry_sync.sh
%
% Agent atom map: registry agent_id → Prolog atom = downcase first letter
%   LegacyCobol → legacyCobol,  Risk → risk,  Quant → quant
% Predicates: agent_id/2, agent/1, control_plane/1, capability/2,
%   permission/2, risk_class/2, depends/2

agent_id('LegacyCobol', legacyCobol).
agent_id('Database', database).
agent_id('ReverseEngineering', reverseEngineering).
agent_id('Modernization', modernization).
agent_id('MigrationValidation', migrationValidation).
agent_id('Provenance', provenance).
agent_id('Risk', risk).
agent_id('Audit', audit).
agent_id('Response', response).
agent_id('Quant', quant).

agent(legacyCobol).
agent(database).
agent(reverseEngineering).
agent(modernization).
agent(migrationValidation).
agent(provenance).
agent(risk).
agent(audit).
agent(response).
agent(quant).

control_plane(risk).
control_plane(audit).
control_plane(response).

capability(legacyCobol, cobol).
capability(legacyCobol, copybook_analysis).
capability(legacyCobol, control_flow).
capability(legacyCobol, data_flow).
capability(legacyCobol, business_rule_extraction).
capability(legacyCobol, modernization_analysis).
capability(database, schema_analysis).
capability(database, db2).
capability(database, sql).
capability(reverseEngineering, call_graph).
capability(reverseEngineering, control_flow).
capability(reverseEngineering, data_flow).
capability(modernization, cobol_to_java).
capability(modernization, api_mapping).
capability(migrationValidation, equivalence).
capability(migrationValidation, behavioral_compare).
capability(provenance, provenance_dag).
capability(provenance, content_hash).
capability(provenance, authority).
capability(risk, risk_policy).
capability(risk, escalation).
capability(audit, audit_trail).
capability(audit, compliance).
capability(response, synthesis).
capability(response, user_response).
capability(quant, pricing).
capability(quant, monte_carlo).
capability(quant, greeks).

permission(legacyCobol, read_source).
permission(legacyCobol, read_copybooks).
permission(database, read_schema).
permission(reverseEngineering, read_source).
permission(modernization, read_source).
permission(modernization, write_plan).
permission(migrationValidation, read_outputs).
permission(provenance, read_evidence).
permission(provenance, write_provenance).
permission(risk, read_all_results).
permission(audit, read_all_results).
permission(response, read_conclusions).
permission(quant, read_market_data).

risk_class(legacyCobol, high).
risk_class(database, medium).
risk_class(reverseEngineering, medium).
risk_class(modernization, high).
risk_class(migrationValidation, high).
risk_class(provenance, medium).
risk_class(risk, critical).
risk_class(audit, high).
risk_class(response, medium).
risk_class(quant, medium).

depends(legacyCobol, database).
depends(legacyCobol, reverseEngineering).
depends(legacyCobol, provenance).
depends(modernization, legacyCobol).
depends(modernization, provenance).
depends(migrationValidation, provenance).
depends(migrationValidation, legacyCobol).
depends(audit, provenance).
