NB. SPDX-License-Identifier: AGPL-3.0-only
NB. Product path: J passes candidates + request into SWI-Prolog eligibility.
NB. Embeddings propose; Prolog decides. No Python in this path.
NB. Atom map: registry id → Prolog atom = downcase first letter (LegacyCobol→legacyCobol).

cocurrent 'david'

NB. Repo root relative to j/ working directory
DAVID_ROOT=: '..'

NB. Registry PascalCase id → Prolog atom (first char only)
to_prolog_atom=: 3 : 0
  s=. ,": y
  if. 0=#s do. '' return. end.
  u=. a. i. {. s
  if. (u >: 65) *. (u <: 90) do.
    ((u + 32) { a.) , }. s
  else.
    s
  end.
)

NB. Write temporary Prolog request facts (plain clauses; preds are dynamic in rules).
NB. y = (<req),(<caps),(<perms),(<maxr),(<cands)
write_request_pl=: 3 : 0
  'req caps perms maxr cands'=. y
  path=. jpath '~temp/david_elig_req.pl'
  try. 1!:55 <path catch. end.
  lines=. 0$a:
  lines=. lines , <('% generated by j/eligibility.ijs — plain facts for dynamic preds')
  for_c. caps do.
    lines=. lines , <('required_capability(', req, ', ', (>c), ').')
  end.
  for_p. perms do.
    lines=. lines , <('granted_permission(', req, ', ', (>p), ').')
  end.
  lines=. lines , <('max_risk_class(', req, ', ', maxr, ').')
  for_a. cands do.
    atom=. to_prolog_atom >a
    lines=. lines , <('ann_candidate(', req, ', ', atom, ').')
  end.
  (; LF ,~ each lines) 1!:2 <path
  path
)

NB. Invoke swipl run_eligibility(Req); return stdout text
NB. y = (<req),(<path)
swipl_eligibility=: 3 : 0
  'req reqpl'=. y
  rules=. DAVID_ROOT , '/router/symbolic_rules.pl'
  goal=. 'consult(''', reqpl, '''), run_eligibility(', req, ')'
  cmd=. 'swipl -q -s ' , rules , ' -g "' , goal , '" -t halt'
  2!:0 cmd
)

NB. Parse selected:[a,b,c] line → boxed atom strings
parse_selected=: 3 : 0
  t=. ,": y
  i=. I. 'selected:' E. t
  if. 0=#i do. 0$<'' return. end.
  rest=. (9 + {.i) }. t
  NB. drop brackets/whitespace; keep commas and atoms
  rest=. rest -. LF , CR , ' []'
  if. 0=#rest do. 0$<'' return. end.
  <;._1 (',', rest)
)

NB. Product entry
NB. y = (<caps),(<perms),(<max_risk),(<cands_registry_ids)
NB. returns boxed selected Prolog atoms
elig_query=: 3 : 0
  'caps perms maxr cands'=. y
  req=. 'j_req'
  path=. write_request_pl (<req),(<caps),(<perms),(<maxr),(<cands)
  out=. swipl_eligibility (<req),(<path)
  try. 1!:55 <path catch. end.
  parse_selected out
)

NB. Load candidate fixture file (one registry id per line; # comments ok)
load_cand_fixture=: 3 : 0
  p=. y
  if. 0=#p do. p=. 'fixtures/ann_topk.txt' end.
  raw=. 1!:1 <p
  lines=. <;._2 raw , LF
  keep=. 0$a:
  for_L. lines do.
    s=. deb >L
    if. (0=#s) +. '#' = {. s , ' ' do. continue. end.
    keep=. keep , <s
  end.
  keep
)
